### ISSUE TITLE
Issue #7 Create the Item Categories page (Mockup)

### ISSUE THREAD

**Issue by matthew-yamaguchi** [manoaswapshop/swapshop_source#8]
Do all work for this task in a branch called issue-07. Create the item categories page mockup, no functionality required.  The item categories will have predetermined categories for the user to choose from such as textbooks, furniture, electronic equipment, etc.

**Comment by kyamagucUHM** [comment]
Category Pages and associated changes set. Possible refining and feature additions at a later date
