### ISSUE TITLE
Issue #8 - Create the Create a Listing page (Mockup)

### ISSUE THREAD

**Issue by matthew-yamaguchi** [manoaswapshop/swapshop_source#9]
Do all work for this task in a branch called issue-08. Create the create a listing page mockup, no functionality required.  On this page, the user will be able to list an item they wish to put up for sale.  

Some features may/will include:
-Requiring a photo of the item (may not apply to services)
-Writing a description of the item
-Selecting from predetermined conditions of the item (New, used, for parts or broken)
-Inputting the desired amount for the item

**Comment by kyamagucUHM** [comment]
Listing Creation Page Complete, Works fully with all drop downs.  Item Description Box will be added later when Item Card Page Enhancement is Deployed.
